services:
  - type: web
    name: project-pet-backend
    env: python
    buildCommand: |
      cd /opt/render/project/src
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: cd /opt/render/project/src && PYTHONPATH=/opt/render/project/src uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src 