services:
  - type: web
    name: project-pet-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: https://project-pet.vercel.app
    healthCheckPath: /ping
    envVars:
      - key: PORT
        value: 10000 